// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7f2bb7d0-e2f8-49c8-80fc-555b7860e0ef",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_XMHgPBUpr",
    "aws_user_pools_web_client_id": "19fej3irt9sgfvr6ljfk5m72nf",
    "oauth": {}
};


export default awsmobile;
